version: '2'
services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  db:
    image: mariadb:10
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./tmp/seeds:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: adonis
      MYSQL_DATABASE: speaker_illus
    ports:
      - 3306:3306

  # api:
  #   build: api
  #   volumes:
  #     - ./api:/usr/src/app
  #   environment:
  #     HOST: 0.0.0.0
  #     PORT: 3333
  #     NODE_ENV: development
  #     APP_NAME: SpeakerWindows
  #     APP_URL: http://${HOST}:${PORT}
  #     CACHE_VIEWS: "false"
  #     APP_KEY: UTSmox4FcCM0G06ErBCyNarbyEcptODB
  #     DB_CONNECTION: mysql
  #     DB_HOST: db
  #     DB_PORT: 3306
  #     DB_USER: root
  #     DB_PASSWORD: adonis
  #     DB_DATABASE: speaker_illus
  #     HASH_DRIVER: bcrypt
  #   ports:
  #     - 3334:3333
