version: '2'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  db:
    image: mysql:8
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./tmp/seeds:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: adonis
      MYSQL_DATABASE: speaker_illus
    ports:
      - 3306:3306

  # adonis_app:
  #   container_name: adonis_app
  #   restart: always
  #   build:
  #     context: api/.
  #     target: dependencies
  #   ports:
  #     - 3333:3333
  #     - 9229:9229
  #   env_file:
  #     - api/.env
  #   volumes:
  #     - ./api/:/home/node/app
  #     # Uncomment the below line if you developing on MacOS
  #     #- /home/node/app/node_modules
  #   command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
