/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  HealthChecks: () => import('#controllers/health_checks_controller'),
  http: {
    Authors: () => import('#controllers/http/authors_controller'),
    Contacts: () => import('#controllers/http/contacts_controller'),
    HybridSearch: () => import('#controllers/http/hybrid_search_controller'),
    Illustrations: () => import('#controllers/http/illustrations_controller'),
    Imports: () => import('#controllers/http/imports_controller'),
    Places: () => import('#controllers/http/places_controller'),
    Settings: () => import('#controllers/http/settings_controller'),
    Tags: () => import('#controllers/http/tags_controller'),
    Teams: () => import('#controllers/http/teams_controller'),
    Uploads: () => import('#controllers/http/uploads_controller'),
    Users: () => import('#controllers/http/users_controller'),
  },
}
