/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  HealthChecks: () => import('#controllers/health_checks_controller'),
  http: {
    Authors: () => import('#controllers/http/AuthorsController'),
    Contacts: () => import('#controllers/http/ContactsController'),
    HybridSearch: () => import('#controllers/http/HybridSearchController'),
    Illustrations: () => import('#controllers/http/IllustrationsController'),
    Places: () => import('#controllers/http/PlacesController'),
    Settings: () => import('#controllers/http/SettingsController'),
    Tags: () => import('#controllers/http/TagsController'),
    Teams: () => import('#controllers/http/TeamsController'),
    Uploads: () => import('#controllers/http/UploadsController'),
    Users: () => import('#controllers/http/UsersController'),
  },
}
